version: '3'
services:
  manage-task:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '1111:1111'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
